import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "./client-layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: {
    default: "Portfolio - Full-Stack Developer & Designer",
    template: "%s | Portfolio",
  },
  description:
    "Showcase of web development projects and case studies. Expert in React, Next.js, TypeScript, and modern web technologies.",
  keywords: ["developer", "portfolio", "React", "Next.js", "web design", "full-stack"],
  authors: [{ name: "Sasithon Marom" }],
  creator: "Sasithon Marom",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://portfolio-nine-snowy-18.vercel.app",
    siteName: "Portfolio",
    title: "Portfolio - Full-Stack Developer & Designer",
    description: "Showcase of web development projects and case studies",
    images: [
      {
        url: "https://portfolio-nine-snowy-18.vercel.app/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Portfolio",
      },
    ],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
    },
  },
  manifest: "/manifest.json",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sans antialiased`}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
